app:
  port: 3000
# Portainer .env DATABASE_HOST: "localhost"
postgres:
  host: "env-2295026.la1.ltccloud.la"
  port: "5432"
  user: "super_admin"
  password: "P@ssw0rd"
  database: "Demo"

minio:
  endpoint: "env-2295026.la1.ltccloud.la:2087"
  accessKeyID: "ZzTlrlqzPXgnymAt"
  secretAccessKey: "K0BprpEjS621xthpGvoInaPoFYlTO9sj"
  bucket: "demo"
